### ISSUE TITLE
Correção do README.md

### ISSUE THREAD

**Issue by esron** [leolleocomp/laravel-for-ninjas#1]
O comando:

`[dentro-do-conteiner]# chmod -R www-data:www-data storage`

deveria ser:

`[dentro-do-conteiner]# chown -R www-data:www-data storage`

Outro comando que retorna uma erro é: 

`docker exec -it laravelforninjas_web_1 bash `

que deveria ser:

`docker exec -it laravel-for-ninjas_web_1 bash`

**Comment by o-leolleo** [comment]
Opa, cara, muito obrigado, foi corrigido!
